# Generated by Django 3.0.11 on 2021-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210125_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginverification',
            name='otp',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='otp',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
