# Generated by Django 3.0.5 on 2021-05-25 06:09

from django.db import migrations, models
import django.db.models.deletion
import login.helper
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('Session_Id', models.CharField(default=login.models.RandomSesssionKey, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=login.models.time_now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.CreateModel(
            name='LoginVerification',
            fields=[
                ('id', models.CharField(default=login.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.CharField(default=login.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('flag', models.CharField(choices=[('0', 'Red'), ('1', 'Yellow'), ('2', 'Green')], default='0', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
        migrations.CreateModel(
            name='KeystrokeDynamics',
            fields=[
                ('id', models.CharField(default=login.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('up_letter_array', models.TextField()),
                ('down_letter_array', models.TextField()),
                ('up_time', models.TextField()),
                ('down_time', models.TextField()),
                ('press_time_array', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
    ]
