# Generated by Django 3.0.5 on 2021-05-16 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210517_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 1, 7, 31, 561704)),
        ),
    ]
