# Generated by Django 3.0.5 on 2021-05-17 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210517_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 0, 40, 16, 571825)),
        ),
    ]
