# Generated by Django 3.0.5 on 2021-05-17 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210518_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 1, 1, 41, 434522)),
        ),
    ]
