# Generated by Django 3.0.5 on 2021-05-15 05:03

from django.db import migrations, models
import django.db.models.deletion
import login.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0006_emailverification_phoneverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginVerification',
            fields=[
                ('id', models.CharField(default=login.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(editable=False, max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.CharField(default=login.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('flag', models.CharField(choices=[('0', 'Red'), ('1', 'Yellow'), ('2', 'Green')], default='0', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
    ]
