# Generated by Django 3.0.5 on 2021-05-16 05:14

from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210516_1044'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginverification',
            name='otp',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('Session_Id', models.CharField(default=login.models.RandomSesssionKey, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(default=login.models.time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
    ]
