# Generated by Django 3.0.5 on 2021-05-16 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210516_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 0, 48, 42, 836724)),
        ),
    ]
