# Generated by Django 3.0.11 on 2021-01-24 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='keystroke_dynamics',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='users.KeystrokeDynamics'),
        ),
    ]
