# Generated by Django 3.0.5 on 2021-05-25 05:24

from django.db import migrations, models
import django.db.models.deletion
import register.helper
import register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HintQuestions',
            fields=[
                ('id', models.CharField(default=register.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=register.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('birthdate', models.DateField(blank=True)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('phone_verified', models.BooleanField(default=False)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('street', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('hint_answer', models.CharField(max_length=100)),
                ('login_country', models.CharField(max_length=50)),
                ('keystroke_prediction', models.IntegerField(default=-1)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=register.models.image_path)),
                ('hint_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.HintQuestions')),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=register.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='register.UserProfile')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.CharField(default=register.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.CharField(default=register.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
    ]
