# Generated by Django 3.0.5 on 2021-05-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='User_Profile',
        ),
    ]
