# Generated by Django 3.0.5 on 2021-05-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210515_0136'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
