# Generated by Django 3.0.5 on 2021-05-14 20:31

from django.db import migrations, models
import django.db.models.deletion
import register.helper


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210515_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=register.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('profile', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='register.UserProfile')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
