# Generated by Django 3.0.5 on 2021-05-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210516_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.User'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='register.UserProfile'),
        ),
    ]
