# Generated by Django 3.0.5 on 2021-03-11 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.helper
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=users.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HintQuestions',
            fields=[
                ('id', models.CharField(default=users.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=users.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('phone_verified', models.BooleanField(default=False)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('street', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('hint_answer', models.CharField(max_length=100)),
                ('login_country', models.CharField(max_length=50)),
                ('keystroke_prediction', models.IntegerField(default=-1)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=users.models.image_path)),
                ('hint_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.HintQuestions')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.CharField(default=users.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(editable=False, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginVerification',
            fields=[
                ('id', models.CharField(default=users.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(editable=False, max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.CharField(default=users.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('flag', models.CharField(choices=[('0', 'Red'), ('1', 'Yellow'), ('2', 'Green')], default='0', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeystrokeDynamics',
            fields=[
                ('id', models.CharField(default=users.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('up_letter_array', models.TextField()),
                ('down_letter_array', models.TextField()),
                ('up_time', models.TextField()),
                ('down_time', models.TextField()),
                ('press_time_array', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.CharField(default=users.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.UserProfile'),
        ),
    ]
