# Generated by Django 3.0.11 on 2021-01-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210124_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='keystroke_dynamics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.KeystrokeDynamics'),
        ),
    ]
