# Generated by Django 3.0.11 on 2021-01-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_log_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_country',
            field=models.CharField(default='India', max_length=50),
            preserve_default=False,
        ),
    ]
