# Generated by Django 3.0.5 on 2021-05-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210125_1815'),
        ('users', '0002_auto_20210124_1058 copy'),
    ]

    operations = [
    ]
