# Generated by Django 3.0.5 on 2021-05-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20210510_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='keystroke_dynamics',
        ),
        migrations.AddField(
            model_name='loginverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loginverification',
            name='otp',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
