# Generated by Django 3.0.5 on 2021-05-14 20:45

from django.db import migrations, models
import django.db.models.deletion
import register.helper


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.CharField(default=register.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(editable=False, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.CharField(default=register.helper.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='register.User')),
            ],
        ),
    ]
