# Generated by Django 3.0.11 on 2021-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210125_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
